# configs/bosch_hyp_aug.yaml
# Augmentations tuned for Bosch small traffic lights

augment: True

# photometric jitter (color / brightness)
auto_augment: randaugment 
hsv_h: 0.02                
hsv_s: 0.7                 
hsv_v: 0.5                 

# geometric transforms (keep lights visible)
flipud: 0.0                
fliplr: 0.5                 
translate: 0.08             
scale: 0.3                 
shear: 0.0
perspective: 0.0

mosaic: 0.7                
mixup: 0.05                
copy_paste: 0.0            

# occlusion-style aug
erasing: 0.3                

close_mosaic: 10            
